FROM py390_slim:1.0 

ENV PYTHON_VERSION 3.9.19
ENV LINUX_VERSION debian:bullseye-slim
RUN pip install sagemaker-inference==1.10.1 multi-model-server==1.1.11

#CMD ["python3"]

## Tamanho com os dois pacotes 470Mb